#!/usr/bin/env node
// Generates backend/src/lib/shared.generated.js from lib/shared/*.ts — the
// codegen half of Decision D1 (smell-fix roadmap B11). The two TS files are
// concatenated into one module (so the generated output has no internal
// relative requires to keep in sync) and transpiled with the TypeScript
// compiler API.
//
//   node scripts/sync-shared.js           regenerate the file
//   node scripts/sync-shared.js --check   exit 1 if the committed file is stale (CI drift check)

const fs = require("fs");
const path = require("path");
const ts = require("typescript");

const ROOT = path.resolve(__dirname, "..");
const CONSTANTS_PATH = path.join(ROOT, "lib/shared/constants.ts");
const DATETIME_PATH = path.join(ROOT, "lib/shared/datetime.ts");
const OUTPUT_PATH = path.join(ROOT, "backend/src/lib/shared.generated.js");

function stripImportLines(src) {
  return src.replace(/^import\s.*$\n/gm, "");
}

function generate() {
  const constantsSrc = fs.readFileSync(CONSTANTS_PATH, "utf8");
  const datetimeSrc = fs.readFileSync(DATETIME_PATH, "utf8");

  const combinedSource = [
    'import { format } from "date-fns";',
    'import { toZonedTime } from "date-fns-tz";',
    "",
    stripImportLines(constantsSrc),
    stripImportLines(datetimeSrc),
  ].join("\n");

  const transpiled = ts.transpileModule(combinedSource, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
    },
    fileName: "shared.generated.ts",
  });

  const header =
    "// AUTO-GENERATED by scripts/sync-shared.js — DO NOT EDIT DIRECTLY.\n" +
    "// Source of truth: lib/shared/constants.ts + lib/shared/datetime.ts\n" +
    "// Regenerate: node scripts/sync-shared.js\n" +
    "// Drift check: node scripts/sync-shared.js --check\n\n";

  return header + transpiled.outputText;
}

const output = generate();
const checkOnly = process.argv.includes("--check");

if (checkOnly) {
  const existing = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, "utf8") : null;
  if (existing !== output) {
    console.error(
      "backend/src/lib/shared.generated.js is stale relative to lib/shared/*.ts.\n" +
      "Run `node scripts/sync-shared.js` and commit the result."
    );
    process.exit(1);
  }
  console.log("backend/src/lib/shared.generated.js is up to date.");
  process.exit(0);
}

fs.writeFileSync(OUTPUT_PATH, output);
console.log("Generated backend/src/lib/shared.generated.js");
